[package]
name = "mongodm"
version = "0.1.0"
authors = ["Benoît CORTIER <benoit.cortier@fried-world.eu>"]
edition = "2018"
description = "A thin ODM layer for mongodb"
license = "MIT OR Apache-2.0"

[dependencies]
mongodb = { version = "1", features = ["tokio-runtime"] }
serde = { version = "1", features = ["derive"] }
futures-core = "0.3"

[dev-dependencies]
tokio = "0.2"
pretty_assertions = "0.6"

[features]
default = ["tokio-runtime"]
tokio-runtime = ["mongodb/tokio-runtime"]
async-std-runtime = ["mongodb/async-std-runtime"]
